services:
  - type: web
    name: analyseur-fichiers
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: RENDER_DISK_PATH
        value: /var/data/uploads
    disks:
      - name: uploads-disk
        mountPath: /var/data/uploads
        sizeGB: 1